apiVersion: v1
kind: Service
metadata:
  name: web-backend-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: web-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  
