apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-backend
  template:
    metadata:
      labels:
        app: web-backend
    spec:
      containers:
        - name: web-backend
          image: gcr.io/infra-deploy-394001/web-backend:latest
          ports:
            - containerPort: 3000