apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-frontend-stage
  template:
    metadata:
      labels:
        app: web-frontend-stage
    spec:
      containers:
        - name: nodejs-web
          image: gcr.io/infra-deploy-394001/web-frontend:latest
          ports:
            - containerPort: 3000